package com.bkrmalick.awsimageupload.profile;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.bkrmalick.awsimageupload.config.AmazonConfig;

import java.io.Serializable;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;

@DynamoDBTable(tableName="UserProfile")
public class UserProfile implements Serializable
{
	private String userProfileID;
	private String username;
	private String userProfileImageLink; //S3 Key
	private Integer score;


	public UserProfile(String username, String userProfileImageLink, int score)
	{
		this.userProfileID =UUID.randomUUID().toString();
		this.username = username;
		this.userProfileImageLink = userProfileImageLink;
		this.score=score;
	}

	public UserProfile()
	{
		this.userProfileID =null;
		this.username="";
		this.userProfileImageLink = "";
		this.score=0;
	}

	public void setUserProfileID(String userProfileID)
	{
		this.userProfileID = userProfileID;
	}

	public void setUsername(String username)
	{
		this.username = username;
	}

	public void setScore(Integer score)
	{
		this.score = score;
	}

	@DynamoDBHashKey(attributeName = "userProfileID")
	@DynamoDBAutoGeneratedKey
	public String getUserProfileID()
	{
		return userProfileID;
	}

	@DynamoDBAttribute
	public String getUsername()
	{
		return username;
	}

	@DynamoDBAttribute
	public String getUserProfileImageLink()
	{
		return userProfileImageLink;
	}
/*
	public Optional<String> getUserProfileImageLink()
	{
		return Optional.ofNullable(userProfileImageLink);
	}
*/
	@DynamoDBAttribute
	public int getScore()
	{
		return score;
	}

	public void setUserProfileImageLink(String userProfileImageLink)
	{
		this.userProfileImageLink = userProfileImageLink; //AmazonConfig.getURL(path+"/"+filename);
	}

	public void setScore(int score)
	{
		this.score = score;
	}

	@Override
	public int hashCode()
	{
		return Objects.hash(userProfileID, username, userProfileImageLink, score);
	}

	@Override
	public boolean equals(Object o)
	{
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		UserProfile that = (UserProfile) o;
		return Objects.equals(userProfileID, that.userProfileID) &&
				Objects.equals(username, that.username) &&
				Objects.equals(userProfileImageLink, that.userProfileImageLink)&&
				Objects.equals(score, that.score);
	}
}
